/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_quadroid_ContextSwitchMeasurement_ndk_Switch */

#ifndef _Included_io_quadroid_ContextSwitchMeasurement_ndk_Switch
#define _Included_io_quadroid_ContextSwitchMeasurement_ndk_Switch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_quadroid_ContextSwitchMeasurement_ndk_Switch
 * Method:    roundtrip
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_quadroid_ContextSwitchMeasurement_ndk_Switch_roundtrip
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_quadroid_ContextSwitchMeasurement_ndk_Switch
 * Method:    post
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_quadroid_ContextSwitchMeasurement_ndk_Switch_post
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_quadroid_ContextSwitchMeasurement_ndk_Switch
 * Method:    get
 * Signature: (J)Z
 */
JNIEXPORT void JNICALL Java_io_quadroid_ContextSwitchMeasurement_ndk_Switch_get
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
