/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_quadroid_ContextSwitchMeasurement_ndk_Switch */

#ifndef _Included_io_quadroid_ContextSwitchMeasurement_ndk_Switch
#define _Included_io_quadroid_ContextSwitchMeasurement_ndk_Switch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_quadroid_ContextSwitchMeasurement_ndk_Switch
 * Method:    jniFromJavaToC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_quadroid_ContextSwitchMeasurement_ndk_Switch_jniFromJavaToC
  (JNIEnv *, jclass);

/*
 * Class:     io_quadroid_ContextSwitchMeasurement_ndk_Switch
 * Method:    jniFromCToJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_quadroid_ContextSwitchMeasurement_ndk_Switch_jniFromCToJava
  (JNIEnv *, jclass);

/*
 * Class:     io_quadroid_ContextSwitchMeasurement_ndk_Switch
 * Method:    jniStartAccelerometer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_quadroid_ContextSwitchMeasurement_ndk_Switch_jniStartAccelerometer
  (JNIEnv *, jclass);

/*
 * Class:     io_quadroid_ContextSwitchMeasurement_ndk_Switch
 * Method:    jniStopAccelerometer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_quadroid_ContextSwitchMeasurement_ndk_Switch_jniStopAccelerometer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
